### ISSUE TITLE
HTML publishing

### ISSUE THREAD

**Issue by enigtique** [kibook/s1kd-tools#1]
Hello, 
I'm very interesting by your project.
Have you the project to include an HTML publishing in your project ?

Thanks

**Comment by kibook** [comment]
Hello, and thanks for your interest!

For the most part, these tools take S1000D input and produce S1000D output, so there is nothing specifically related to HTML publishing. However, they are designed to be a part of that process.

For example, if you need to filter your data modules for different customers, you can use the [s1kd-instance](https://github.com/kibook/s1kd-tools/tree/master/tools/s1kd-instance) tool to create a filtered S1000D data set, and then use an S1000D-to-HTML stylesheet to produce HTML output from that data set. However, this project doesn't contain such a stylesheet.

I have a couple rough examples of stylesheets that might interest you. These are nowhere near complete, however:

- https://github.com/kibook/s1000d-html-stylesheet - S1000D-to-HTML (very basic)
- https://github.com/kibook/s1kd2db - S1000D-to-DocBook (and there are several existing options to publish HTML from DocBook)

**Comment by enigtique** [comment]
Thank you for your reply.

I'm working in a company and we generated technical publications in s1000D for aircraft. 

We only have authoring software but no really complete system to manage all dms or cmp.

I make my proper tools in vba and my soft do the same like your soft but very shipest than your soft. 

Thank you for your links and sorry for my English.

**Comment by kibook** [comment]
It's no trouble! I'm always interested to hear from another S1000D user. If you have any questions about any part of this project, feel free to create an issue or send me an email.
