### ISSUE TITLE
Regex Rules incorrectly matched

### ISSUE THREAD

**Issue by MihailCosmin** [kibook/s1kd-tools#12]
Hi,

I've been using the brex checker to check some DMs and for some reason below regex rule is always marked as violated, even when it shouldn't:

```
<structureObjectRule>
<objectPath allowedObjectFlag="2">//catalogSeqNumber/itemSeqNumber/partRef/@partNumberValue</objectPath>
<objectUse>The @partNumberValue attribute within the &lt;itemSeqNumber&gt;&lt;partRef&gt; element must be 1 to 15 characters long and only include A to Z (excluding "O" (oh)), 0 to 9, and "-" (hyphens).</objectUse>
<objectValue valueAllowed="^[-A-Z0-9-[O]]{1,15}$" valueForm="pattern"/>
</structureObjectRule>
```
This says cases like: LN9499-01-45 or NAS1833C08-370 do not match the pattern.

At first I thought this was because the regex processor you are using cannot handle cases like -[O] which excludes the letter O.

But even after manually adjusting the regex in the BREX to:
`^[-A-NP-Z0-9]{1,15}$`
This still marks everything as wrong (not matching the regex).

Do you have any idea why this happens?

**Comment by kibook** [comment]
I believe the issue is that the anchors (`^` and `$`) are not allowed by the form of regular expressions the libxml2 regular expression engine parses, which is also the form that the S1000D specification refers to for `"pattern"` object values in the BREX.

S1000D 5.0, Chap 4.10.2.2:
> A pattern should be provided as a regular expression in accordance with "REC-xmlschema-2-20041028 "W3C Recommendation: XML Schema Part 2: Datatypes Second Edition (2004 Second Edition)".

[XML Schema Part 2: Datatypes, Appendix F Regular Expressions](https://www.w3.org/TR/xmlschema-2/#regexs):
> Unlike some popular regular expression languages (including those defined by Perl and standard Unix utilities), the regular expression language defined here implicitly anchors all regular expressions at the head and tail, as the most common use of regular expressions in [·pattern·](https://www.w3.org/TR/xmlschema-2/#dt-pattern) is to match entire literals. For example, a datatype [·derived·](https://www.w3.org/TR/xmlschema-2/#dt-derived) from [string](https://www.w3.org/TR/xmlschema-2/#string) such that all values must begin with the character A (#x41) and end with the character Z (#x5a) would be defined as follows:
>
>```xml
><simpleType name='myString'>
> <restriction base='string'>
>  <pattern value='A.*Z'/>
> </restriction>
></simpleType>
>```
>
>In regular expression languages that are not implicitly anchored at the head and tail, it is customary to write the equivalent regular expression as:
>
> ```
>   ^A.*Z$
>```
>
>where "^" anchors the pattern at the head and "$" anchors at the tail.
>
>In those rare cases where an unanchored match is desired, including .* at the beginning and ending of the regular expression will achieve the desired results.

So, those anchor characters are not needed because all expressions are implicitly anchored.

**Comment by MihailCosmin** [comment]
Indeed removing the achor characters fixes the issue.
I only had them for one regex, which is strange since this was an official BREX from ATA.
